apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels: 
    componentkub: web
spec:
  containers:
    - name: client
      image: saarthak08/complex-multistage-docker-client
      ports: 
        - containerPort: 3000
